name: expense_tracker_mobile
description: "A new Flutter project."
publish_to: "none"
version: 1.3.0+7

environment:
  sdk: ^3.9.2

dependencies:
  animated_toggle_switch: ^0.8.5
  dio: ^5.9.0
  equatable: ^2.0.7
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.1
  get_it: ^8.2.0
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  network_logger: ^1.0.4
  package_info_plus: ^9.0.0
  retrofit: ^4.7.2
  sentry_flutter: ^9.6.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.7.1
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1
  retrofit_generator: ^10.0.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/env/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
